#!/bin/bash
# Concatenates colors + icon_map + icon_builder + aerospace into one file.
# Eliminates 3 source calls on every event. Run by sketchybarrc on reload.
# Order: constants → function defs → event handler logic.
# Output is gitignored (plugins/aerospace_compiled.sh).

CONFIG_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="$CONFIG_DIR/plugins/aerospace_compiled.sh"

{
  echo '#!/bin/bash'
  echo ''
  echo '# AUTO-GENERATED by build.sh — do not edit directly'
  echo ''

  # Strip shebangs; strip source lines from files that have them
  grep -v '^#!/bin/bash' "$CONFIG_DIR/colors.sh"
  echo ''
  grep -v '^#!/bin/bash' "$CONFIG_DIR/plugins/icon_map_fn.sh"
  echo ''
  grep -v '^#!/bin/bash' "$CONFIG_DIR/plugins/icon_builder.sh" | grep -v '^source '
  echo ''
  grep -v '^#!/bin/bash' "$CONFIG_DIR/plugins/aerospace.sh" | grep -v '^source '

} > "$OUTPUT"

chmod +x "$OUTPUT"
